---
 models_path: "./models"
 output_path: "./output"
 model_config: "v1-inference.yaml" #@param ["custom","v1-inference.yaml"]
 model_checkpoint: "custom" #@param ["custom","sd-v1-4-full-ema.ckpt","sd-v1-4.ckpt",...]
 custom_config_path: "" #@param {type:"string"}
 custom_checkpoint_path: = "./models/friyo.ckpt" #@param {type:"string"} 
 precision: "full"        # fp16 full
 video: 
   fps: 60
   format: "mp4"
 dry_run: "no"
 total_time: 3:26:00.00
 default:
   angle: 0.0
   scale: 1
   translation_x: 0
   translation_y: 0
   strength_schedule: 0.65
   noise_schedule: 0.02
   contrast_schedule: 1.0

scenes:
   - "0:00:00.00|0.0|1|0|1|0.8||a friyo playing piano on the beach"
   - "0:00:10.30|0.0|1|0|0|0.5||a friyo playing guitar on sunflowers at starry night"
   - "0:00:20.00|0.0|1|0|0|0.65||a friyo playing smoking a joint in the space"
